# Generated by Django 3.1.5 on 2022-12-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0002_reportmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reportModel',
        ),
    ]
