# Generated by Django 3.1.5 on 2023-01-03 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0007_detectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionmodel',
            name='id',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
