# Generated by Django 3.1.5 on 2023-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0008_detectionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionmodel',
            name='id',
            field=models.IntegerField(),
        ),
    ]
